###Solution's to The Given Assignment!

In [6]:
import tensorflow as tf
import tensorflow_probability as tfp
import numpy as np
import numba

In [13]:
#Problem 1
@tf.function(autograph=False)
def sum_cos_sin(x, coeff_cos, coeff_sin):
    """Return the sum of the cos and sin of x element-wise, cos and sin scaled by coeff_cos and coeff_sin respectively."""
    #First we assign s1 as a variable for sin of x element,scaled by coeff_sin
    s1=tf.math.sin(tf.math.abs(x))/coeff_sin
    #Secondly we assign s2 as a variable for cos of x element,scaled by coeff_cos
    s2=tf.math.cos(tf.math.abs(x))/coeff_cos
    #Return the sum of s1 and s2
    return s1+s2
    pass

In [15]:
#The Answer for the First Problem

print(sum_cos_sin(0.0,1.0,1.0))

tf.Tensor(1.0, shape=(), dtype=float32)


In [77]:
#Problem 2
@tf.function(autograph=False)
def approx_cos_p1(x):
    """Return the approximation of cos(x) + 1 using a taylor/series expansion up to order 7"""
    #As we are required to find cos(x)+1 using Taylor Series Expansion Method..we intialize cos_approx=1.0
    x = x * (3.142 / 180.0); 
    cos_approx=tf.constant(1.)
    res = 1;
    sign = 1; 
    fact = 1;
    pow = 1;
    order=7
    for i in range(1,order):
        sign = sign*(-1);
        fact = fact*(2*i-1)*(2*i);
        pow = pow*x*x;
        res = res + sign * pow / fact;
        
    cos_approx+=res
    return cos_approx

In [74]:
x=tf.constant(2.)
print(approx_cos_p1(x))

tf.Tensor(1.9993907, shape=(), dtype=float32)


In [69]:
#Problem 2 without Tensorflow
import math

def func_cos(x, n):
    cos_approx = 1
    x=x*(3.142/180)
    for i in range(n):
        coef = (-1)**i
        num = x**(2*i)
        denom = math.factorial(2*i)
        cos_approx =cos_approx+(coef)*((num)/(denom))
    
    return cos_approx

In [70]:
print(func_cos(2,7))

1.9993906690512515


In [11]:
#Problem 3
@tf.function(autograph=False)
def integral_exp():
    """Integrate the exponential function from lower to upper."""
    def f(x):
      return tf.math.exp(x)
    
    lower=0.0                         #Lower Bound
    upper=5.0                         #Upper Bound
    
    F_int=0
    dx=0.01
    x=lower
    while x<upper:
      f_n = f(x)                       #Call the exp function
      f_n_plusdx = f(x+dx)
      dF = 0.5*(f_n+f_n_plusdx)*dx     # calc the trapezoid area
      F_int += dF                      # sum of the integration
      x+=dx                            # next dx.

    return F_int

In [12]:
integral_exp()

#I was facing some issues related to giving the function call the lower and upper parameters so I shifted them inside the function definition itself

<tf.Tensor: shape=(), dtype=float32, numpy=148.90593>

In [13]:
#Problem 3
#Without Tensorflow
from scipy.integrate import quad
def integrand(t, n, x):
    return math.exp(-x*t)/ t**n

def expint(n, x):
  return quad(integrand, 1, 2, args=(n, x))[0]

vec_expint = np.vectorize(expint)

vec_expint(3,np.arange(1.0,4.0,0.5))

#I tried to find resources for this problem with tensorflow but was unable to find something relevant,I found out integral function using scipy for the same though

array([0.10215862, 0.05450683, 0.02944304, 0.01607592, 0.0088595 ,
       0.00492196])

In [33]:
#Problem 4
@tf.function(autograph=False)
def normed_exp(x):
    """Calculate the normalized exp function `exp(x) / integral exp from lower to upper."""
    def f(x):
      return tf.math.exp(x)           #Exponential function
    
    lower=0.0                         #Lower Bound
    upper=5.0                         #Upper Bound
    F_int=0                           #value of Integral Intially
    dx=0.01                           #dx
    x=lower
    #Calculating the integral
    while x<upper:
      f_n = f(x)                       #Call the exp function
      f_n_plusdx = f(x+dx)
      dF = 0.5*(f_n+f_n_plusdx)*dx     # calc the trapezoid area
      F_int += dF                      # sum of the integration
      x+=dx                            # next dx.

    #Normalizing by diving exp(x) with the integral value of exp(x) from lower to upper bound
    res=f(x)/F_int        #Normalized 

    return res

In [34]:
normed_exp(x=tf.constant(2.))

<tf.Tensor: shape=(), dtype=float32, numpy=1.0067079>

In [82]:
#Problem 4 Method 2
@tf.function(autograph=False)
def normed_exp(x):
    """Calculate the normalized exp function `exp(x) / integral exp from lower to upper`"""
    from scipy import integrate
    #Defining the function of whose integration we need to find
    def f(a):
        return tf.math.exp(a)
    #Doing the Integration
    def integrated(f,x):
        return tf.map_fn( lambda y: tf.py_function(lambda z: integrate.quad( f,0,z)[ 0 ], [ y ], tf.float64 ),x)
    #Calling for the integrated function to calculate the integration of exp(x) from 1.0 to 5.0 for our input[where lower bound=1.0 and upper bound=5.0]
    i=integrated(f,x)
    #Returning the value of integration
    return i



In [83]:
#Taking the Input
x = tf.constant([1.0, 2.0, 3.0, 4.0,5.0], dtype = tf.float64 )
#Output
print(normed_exp(x))


tf.Tensor([  1.71828183   6.38905612  19.08553659  53.5981502  147.41315804], shape=(5,), dtype=float64)


In [25]:
#Problem 5
@tf.function(autograph=False)
def cos_exp(x):
    """Return the elementwise value of the function 'sum_cos_sin(x) for x < - 1; exp(x) for -1 < x < 3; cos(x) for x > 3."""
    if x<-1:
      y1=sum_cos_sin(x,1.0,1.0)
      return y1
    elif x>-1 and x<3:
      y2=tf.math.exp(x)
      return y2
    else:
      y3=tf.math.cos(x)
      return y3
    pass

In [26]:
#Output for Input>3
cos_exp(4.)

<tf.Tensor: shape=(), dtype=float32, numpy=-0.6536436>

In [27]:
#Output for Input<-1
cos_exp(-2.)

<tf.Tensor: shape=(), dtype=float32, numpy=0.49315056>

In [64]:
#Output for Input lying bet -1 and 3
cos_exp(2.)

<tf.Tensor: shape=(), dtype=float32, numpy=7.389056>

In [80]:
#Problem 6
@tf.function(autograph=False)
@tf.custom_gradient
def approx_cos_p1_custom_grad(x):
    """Return the approximation of cos(x) + 1 using a taylor/series expansion up to order 7 **with a custom gradient**"""
    def grad(dy):
      dy_dx=-tf.math.sin(x)
      return dy*dy_dx
    z=approx_cos_p1(x)
    return z,grad
x=tf.constant(2.0,dtype=tf.float32)
with tf.GradientTape(persistent=True) as tape:
  tape.watch(x)
  z =approx_cos_p1_custom_grad(x)
z


<tf.Tensor: shape=(), dtype=float32, numpy=1.9993907>

In [81]:
#Problem 7
#Importing Libraries
from abc import ABC, abstractmethod
#The abstract class Func
class Func(ABC):
    @abstractmethod
    def value(self, x):
        pass

    @abstractmethod
    def integral(self, lower, upper):
        pass
#Our defined class CosFunc that inherits from the abstract class Func
class CosFunc(Func):
  def __init__(self):
    pass
#Value Function returns value of cos(omega) by taking 1 value/omega
  def value(self,omega):
    print(tf.math.cos(omega))
#Integral calculates the integral value of cos(x) from a lower to upper bound
  def integral(self,lower,upper):

    def f(x):
      return tf.math.cos(x)
    
    F_int=0
    dx=0.01
    x=lower
    while x<upper:
      f_n = f(x)                       #Call the cos(x) function
      f_n_plusdx = f(x+dx)
      dF = 0.5*(f_n+f_n_plusdx)*dx     # calc the trapezoid area
      F_int += dF                      # sum of the integration
      x+=dx                            # next dx.

    print(F_int)

In [170]:
#Output
y=CosFunc()
y.value(omega=tf.constant(2.))      #Value of o/p for omega in degrees
y.integral(lower=tf.constant(0.),upper=tf.constant(5.))

tf.Tensor(-0.41614684, shape=(), dtype=float32)
tf.Tensor(-0.95890707, shape=(), dtype=float32)


In [87]:
#The abstract class Func
class PDF(CosFunc):
    @abstractmethod
    def normed_value(self, x):
        pass
class CosPDF(PDF):
  def __init__(self):
    pass
  def normed_value(self,x,lower,upper):
    def f(x):
      return x
    F_int=0
    dx=0.01
    x=lower
    while x<upper:
      f_n = f(x)                       #Call the function which is x
      f_n_plusdx = f(x+dx)
      dF = 0.5*(f_n+f_n_plusdx)*dx     # calc the trapezoid area
      F_int += dF                      # sum of the integration
      x+=dx                            # next dx.

    print(F_int)

In [167]:
cos_pdf=CosPDF()
cos_pdf.normed_value(tf.constant(2.),tf.constant(0.),tf.constant(3.))
#I changed the code a little bit instead of inheriting the values from Func for the PDF class I inherited from the CosFunc class to instantiate the lower and upper values to calculate the integral of x

tf.Tensor(4.530047, shape=(), dtype=float32)


In [84]:
@tf.function(autograph=False)
def log_abs(x):
    return tf.math.log(tf.math.abs(x))

In [88]:
if __name__ == '__main__':
    # test the functions here
    # it should work for both `x`
    use_single_val = True
    if use_single_val:
        x = tf.constant(1., dtype=tf.float64)
        lower = tf.constant(0.3, dtype=tf.float64)
        upper = tf.constant(5., dtype=tf.float64)
        coeff_sin = tf.constant(3.1, dtype=tf.float64)
        coeff_cos = tf.constant(2.1, dtype=tf.float64)
    else:
        shape = (10, 3)
        x = tf.random.uniform(shape=shape, minval=-4.5, maxval=2.3)
        lower = tf.random.uniform(shape=shape, minval=-5.5, maxval=-5.3)
        upper = tf.random.uniform(shape=shape, minval=4.1, maxval=5.2)
        coeff_sin = tf.random.uniform(shape=shape, minval=3.1, maxval=5.2)
        coeff_cos = tf.random.uniform(shape=shape, minval=1.2, maxval=2.23)
    print(log_abs(x))

    with tf.GradientTape() as tape:
        tape.watch(x)
        # your function here
        y = log_abs(x)
    grad = tape.gradient(y, x)
    print(grad)

    cos_func =CosFunc()
    cos_val =cos_func.value(tf.constant(3.))
    cos_pdf =CosPDF()
    cos_pdf.normed_value(tf.constant(2.),tf.constant(0.),tf.constant(3.))

tf.Tensor(0.0, shape=(), dtype=float64)
tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor(-0.9899925, shape=(), dtype=float32)
tf.Tensor(4.530047, shape=(), dtype=float32)
